---
abstract: 'Require logged-in user for specified routes'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0.19
  LWP::UserAgent: 0
  Test::More: 0.96
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Auth-Tiny
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dancer::Plugin::Auth::Tiny:
    file: lib/Dancer/Plugin/Auth/Tiny.pm
    version: 0.002
requires:
  Carp: 0
  Dancer: 0
  Dancer::Plugin: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/dancer-plugin-auth-tiny/issues
  homepage: https://metacpan.org/release/Dancer-Plugin-Auth-Tiny
  repository: git://github.com/dagolden/dancer-plugin-auth-tiny.git
version: 0.002
